### ISSUE TITLE
Error when trying to start locally on OSX.

### ISSUE THREAD

**Issue by bjarnil** [heroku/java-getting-started#70] opened 2018-10-13 18:20 UTC
Hi there,

I'm new to Heroku.  Been trying to setup this tutorial and I keep getting this error when trying to start this up locally on OSX.
```
heroku local:start
[OKAY] Loaded ENV .env File as KEY=VALUE Format
6:16:24 PM web.1 |  Exception in thread "main" 
6:16:24 PM web.1 |  java.lang.reflect.InvocationTargetException
6:16:24 PM web.1 |  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
6:16:24 PM web.1 |  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
6:16:24 PM web.1 |  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
6:16:24 PM web.1 |  	at java.lang.reflect.Method.invoke(Method.java:498)
6:16:24 PM web.1 |  	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
6:16:24 PM web.1 |  	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
6:16:24 PM web.1 |  	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
6:16:24 PM web.1 |  	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
6:16:24 PM web.1 |  Caused by: java.lang.IllegalAccessError: tried to access method org.springframework.core.io.support.SpringFactoriesLoader.loadFactoryNames(Ljava/lang/Class;Ljava/lang/ClassLoader;)Ljava/util/List; from class org.springframework.boot.SpringApplication
6:16:24 PM web.1 |  	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:426)
6:16:24 PM web.1 |  	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:418)
6:16:24 PM web.1 |  	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:266)
6:16:24 PM web.1 |  	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:247)
6:16:24 PM web.1 |  	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
6:16:24 PM web.1 |  	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
6:16:24 PM web.1 |  	at com.example.Main.main(Main.java:48)
6:16:24 PM web.1 |  	... 8 more
[DONE] Killing all processes with signal  SIGINT
6:16:24 PM web.1 Exited with exit code null
```

Any ideas on how to solve this problem?  Works fine when submitted to Heroku.

**Comment by jonmountjoy** [comment] 2019-09-19 10:16
I can't reproduce this so am closing - hope all is well!

**Closed by jonmountjoy** 2019-09-19 10:16 UTC
